spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          adfs:
            clientName: AD FS on Windows Server 2016
            scope: openid, profile
            client-authentication-method: form
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          adfs:
            authorizationUri: https://192.168.33.89/adfs/oauth2/authorize?resource=https://192.168.33.89/adfs/services/trust
            tokenUri: https://192.168.33.89/adfs/oauth2/token
            userInfoUri: https://192.168.33.89/adfs/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://192.168.33.89/adfs/discovery/keys

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8443
  ssl:
    key-alias: weissr
    key-store: C:\projects\oauth-test\weissr.jks
    key-store-password: 1password!
    key-password: 1password!
    trust-store: C:\projects\oauth-test\weissr.jks
    trust-store-password: 1password!
    enabled: true